
##
## This is the library we are making
##
TARGET = libstm32f4xx_usbotg.a
CINCLUDES += -I../STM32F4xx_StdPeriph_Driver/inc/
CFLAGS += -DUSB_OTG_HS_CORE
TARGET_DIR = lib
LIBRARY = 1

include ../Makefile.stm32f4

