
##
## Name of our project and executable
##
CPU = stm32f4
MCPU = cortex-m4
MANUFACTURER = stm32
REVISION = f4
LIBOPENCM3_DEFINE_CPU = STM32F4
BOARD = $(CPU)_discovery_board
LIBRARY = $(LIB_DIR)/lib$(BOARD).a

include ../Makefile.stm32f4

library: $(LIBRARY) 






