
##
## Name of our project and executable
##
TARGET = main
FLASH_START = 0x8000000
CPU = stm32f4
MCPU = cortex-m4
MANUFACTURER = stm32
REVISION = f4
LIBOPENCM3_DEFINE_CPU = STM32F4

include ../Makefile.include

all: $(LIST_FILE) $(HEX_FILE) $(SREC_FILE) $(BIN_FILE)


