DROP TABLE IF EXISTS "webserver";

CREATE TABLE "webserver"(
 ID INTEGER PRIMARY KEY,
 WEBSERVER_USER_NAME TEXT,
 WEBSERVER_PASSWORD TEXT
);

INSERT into webserver (WEBSERVER_USER_NAME, WEBSERVER_PASSWORD) VALUES ("ptracton", "ucla");
